SDK-1853: Add github workflows for tests and sonar
getyoti/yoti-python-sdk pull request #277
Opened 2020-12-11 00:35 UTC by emmas-yoti

2020-12-14 18:54 UTC, echarrod requested changes
Please could we add a compatibility check for Python 3.9 now as well. 

I also don't think it gives us much benefit running the checks on the non-newest dev version:
![image](https://user-images.githubusercontent.com/1381991/102122530-7e6e0a00-3e3d-11eb-997f-36f749732d93.png)
(from https://python.domainunion.de/downloads/)
These older versions will only have security releases, so I think we're still safe to just run against dev in the latest two, maybe even just the latest one

2020-12-15 15:57 UTC, gautam-yoti approved these changes
Haven't worked on workflow setup, but LGTM 👍

2021-01-12 14:52 UTC, echarrod approved these changes
Looks good now :ok_hand: nice work Emma

2021-01-12 14:54 UTC, echarrod commented
Just remembered, we'll need to update the Travis badge in the README too

2021-01-14 15:24 UTC, echarrod requested changes
Badge needs to be updated from Travis to Github too :+1:

2021-02-02 11:48 UTC, echarrod requested changes

2021-02-02 11:48 UTC, echarrod commented on README.md
> +[![Build Status](https://github.com/getyoti/yoti-python-sdk/workflows/Unit%20Test/badge.svg?branch=master)](https://github.com/getyoti/yoti-python-sdk/actions)
You can test these out with the current branch to check they work, before we merge into development (I checked <https://github.com/getyoti/yoti-python-sdk/workflows/Unit%20Test/badge.svg?branch=sdk-1853-github-actions>):
```suggestion
[![Build Status](https://github.com/getyoti/yoti-python-sdk/workflows/Unit%20Tests/badge.svg?branch=master)](https://github.com/getyoti/yoti-python-sdk/actions)
```

2021-03-15 18:13 UTC, echarrod approved these changes
Looks good, we can check the coverage is working in a future PR where we have Python files

2021-03-16 09:48 UTC, merged